# Generated by Django 5.1.5 on 2025-02-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('bieg', 'Bieg'), ('rower', 'Rower'), ('nordic_walking', 'Nordic Walking')], default='bieg', max_length=20),
        ),
    ]
